import { GoogleGenAI, Modality } from "@google/genai";

export const generateImageForItem = async (itemName: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  const response = await ai.models.generateContent({
    model: 'gemini-2.5-flash-image',
    contents: {
      parts: [
        { text: `A high-quality, clean, commercial product photograph of a single ${itemName} on a white background, suitable for an e-commerce inventory system.` }
      ]
    },
    config: {
      responseModalities: [Modality.IMAGE],
    }
  });

  for (const part of response.candidates[0].content.parts) {
    if (part.inlineData) {
      const base64ImageBytes = part.inlineData.data;
      return `data:${part.inlineData.mimeType};base64,${base64ImageBytes}`;
    }
  }
  throw new Error("No image generated by the API.");
};

export const getBusinessSuggestion = async (userPrompt: string, context: string): Promise<string> => {
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  const fullPrompt = `Context:\n${context}\n\nUser Query: ${userPrompt}`;

  const response = await ai.models.generateContent({
    model: 'gemini-2.5-pro',
    contents: fullPrompt,
    config: {
      systemInstruction: `You are an expert business consultant for a small retail shop owner. Your name is Laxs AI.
      Analyze the provided business data context and the user's query to give actionable, concise, and friendly advice.
      Your goal is to help the user improve their sales, manage inventory better, and get new ideas.
      Format your response using markdown with clear headings, lists, and bold text for emphasis.
      Do not mention that you were provided with a context, just use it to inform your answer.`,
    }
  });
  
  return response.text;
};